package main
import "fmt"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
func fib() int {

  // Add the first two terms
  fibo1, fibo2, sum := 1, 2, 2

  for {
    current := fibo1 + fibo2
    fibo1 = fibo2
    fibo2 = current
    if current > 4000000 {
      return sum
    }
    if current % 2 == 0 {
      sum += current
    }
  }
}

func main() {
  sum := fib()
  fmt.Println("The sum of the even valued terms of a fibonacci that does not exceed 4 million is", sum)
}
